# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...

    - name: Generate Test Coverage
      run: go test ./... -coverprofile=./cover.out

    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        # Configure action by specifying input parameters individually (option 2)
        profile: cover.out
        threshold-total: 95

    - name: make coverage badge
      uses: action-badges/core@0.2.2
      # if: contains(github.ref, 'main')
      with:
        label: coverage
        message: ${{ steps.coverage.outputs.badge-text }}
        message-color: ${{ steps.coverage.outputs.badge-color }}
        file-name: coverage.svg
        badge-branch: badges ## orphan branch where badge will be committed
        github-token: "${{ secrets.GITHUB_TOKEN }}"